#!/bin/sh
rm -rf index/*
java -Dio.netty.tryReflectionSetAccessible=false -jar /Users/sam.tingleff/workspaces/personal/yassg/yassg-static/target/yassg-static-1.0.0-jar-with-dependencies.jar -index index/ -semanticUrl $NER_URL -semanticSecret $NER_SECRET -semanticCacheDir semantic-cache/ -content content/ -templates templates/ -output output/

rsync -av static/ output/
