#!/usr/bin/env python
import argparse
import datetime
import os

parser = argparse.ArgumentParser()
parser.add_argument('--content', dest='content', action='store', default='content/blog',
                   help='content directory (default: content/blog)')
parser.add_argument('--author', dest='author', action='store', default='sam',
                   help='page author (default: sam)')
parser.add_argument('--title', dest='title', action='store', default='',
                   help='page title (default: None)')
parser.add_argument('--keywords', dest='keywords', action='store', default='',
                   help='page keywords (default: None)')
parser.add_argument('--description', dest='description', action='store', default='',
                   help='page description (default: None)')
parser.add_argument('--tags', dest='tags', action='store', default='',
                   help='page tags (default: None)')
parser.add_argument('--slug', dest='slug', action='store',
                   help='page slug (default: None)')

args = parser.parse_args()

now = datetime.datetime.now()

content_dir = "%s/%s/%s" % (args.content, now.strftime("%Y/%m/%d"), args.slug)
try: os.makedirs(content_dir)
except OSError: pass

properties_path = "%s/index.properties" % content_dir
body_path = "%s/index.markdown" % content_dir

if os.path.exists(properties_path):
    raise Exception("Properties path %s already exists" % properties_path)
if os.path.exists(body_path):
    raise Exception("Body path %s already exists" % body_path)

f = open(properties_path, "w")
f.write("author = %s\n" % args.author)
f.write("title = %s\n" % args.title)
f.write("keywords = %s\n" % args.keywords)
f.write("description = %s\n" % args.description)
f.write("tags = %s\n" % args.tags)
f.write("href = blog/%s/%s/\n" % (now.strftime("%Y/%m/%d"), args.slug))
f.write("pubDate = %s\n" % now.strftime("%Y-%m-%d %H:%M"))
f.close()

if not os.path.exists(body_path):
    open(body_path, "w").close()

print "Created %s" % body_path
print "Created %s" % properties_path
