<p>Did I say something to offend you? Did you get fired for reading this trash at work and you want to take revenge on my future offspring?</p>
<p>Maybe you just have several million dollars to spare and need to know where to send a check.</p>
<p>Whatever the reason, here's how to get in touch with me. For reference, I promise to keep this page available at <a href="http://sam.tingleff.com/contactsam">http://sam.tingleff.com/contactsam</a>.</p>

<p>My <a href="http://www.jabber.org/user/userfaq.html">Jabber</a> user id is <b>sam at tingleff.com</b> and my <a href="http://www.icq.com/">ICQ</a> # is <b>160876397</b>.</p>

<p>Personal email should be sent to <b>sam at tingleff.com</b> but anything having to do with Viagra or cheap mortage rates can go to <b>spayneti at yahoo.com</b>. If that $10 million is really burning a hole in your pocket my cell phone number is (607) 262-0584.</p>

<p>-Sam</p>
