<p>An ongoing list of states I've been to.</p>

<ol>
 <li>Arizona</li>
 <li>California</li>
 <li>Colorado</li>
 <li>Connecticut</li>
 <li>Florida</li>
 <li>Idaho</li>
 <li>Illinois</li>
 <li>Indiana</li>
 <li>Iowa</li>
 <li>Louisiana</li>
 <li>Maine</li>
 <li>Massachusetts</li>
 <li>Michigan</li>
 <li>Minnesota</li>
 <li>Missouri</li>
 <li>Montana</li>
 <li>New Hampshire</li>
 <li>New Jersey</li>
 <li>New York</li>
 <li>Nevada</li>
 <li>Oregon</li>
 <li>Pennsylvania</li>
 <li>South Dakota</li>
 <li>Texas</li>
 <li>Vermont</li>
 <li>Washington</li>
 <li>Wisconsin</li>
 <li>Wyoming</li>
</ol>
